as yet unclassified
tObjectExecutions

TiPrimitive initialize.
TiSystem current reset.

TObject class methodDict.

Compiler new analyze: ' TObject cascadeTest2' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject simpleAssignement' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject testWhileTrue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnSymbol' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject performReturnArg:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject intermediateRecursion' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject lazyInitializationSucceded' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject dummyBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject initialize' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject testMessage' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnTrue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject dummy' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject multiReturn' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnBlockValue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnArg:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockModifyingArgument' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject succ:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject expression' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject sampleReturnArg' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject selfReturnFive' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject twoBlocks' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject infiniteLoop' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject primitiveMakePoint' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnAssignementInsideBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnArgSends' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockWithArgument' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject screwRandomBoolean:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject primitivePerform' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject unbracedExpression' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject messageInsideABlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject expressionTypeSet' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject id:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject interestingSamples' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject repeatedArgumentNames' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnGlobal' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject esugSample2' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnTrueBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject two' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject variableCascaded' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject willNotUnderstand' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnSelf' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject otherLazyInitializationSucceded' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject forwardMessageTo:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignFromParameter:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignedBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject expressionCascaded' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject bracedExpression' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject multiAssign' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnInsideABlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnString' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject anotherAssignementFromGlobal' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockValue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject impossibleMessage' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject main' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnFive' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject hello' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject lazyAssignement' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject primitiveAdd' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject repeatedSelfArgument' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnStringOrFloatOrSmallInteger' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignInsideBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject messageMax' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject benefitsSample' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject initRandomBoolean' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnArray' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnArgument:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject infiniteRecursion' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockWithHomeRefs' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject randomBoolean' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject sharedObject' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject primitiveFloatAdd' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignementFromGlobal' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject usingABlockReturnArg:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnFalseBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnNil' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject otherLazyInitializationFailed' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject sample1' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnOne' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject one' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject useless' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockReturnOne' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject failedPrimitiveAdd' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject performReturnFive' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject efectoColateral' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject esugSample1' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject flowSensitive' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject doubleNestedBlocks' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject isOdd:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockValue:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject selfCascaded' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignedBlockValue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject nonLocalReturnValue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject bracedExpressionTranslation' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnSomeClasses' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject assignementInsideBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject twoBlocksWithSameLocalVariable' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject simpleProgram' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnSymbolOrString' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject testPoint' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnWithMessageInsideABlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnParameter:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject sevenMax:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject testIfTrue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject challenger' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockAssignements' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject fakeCascadedMessage' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject impossibleMessage:' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject nonLocalReturn' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject implicitReturn' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject indirectReturnOne' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject samplePrimitive' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockWithArgumentValue' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject primitiveNextPut' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject blockWithManyArguments' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject testWhileTrue2' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject repeatedAssignement' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject multiBlockReturns' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject conditionalBlock' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject new' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject indirectRecursion' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject returnBracedArray' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject someWillNotUnderstand' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject lazyInitializationFailed' in: nil to: nil notifying: nil ifFail: [1].

TiSystem current reset.

Compiler new analyze: ' TObject screwRandomBoolean' in: nil to: nil notifying: nil ifFail: [1].

