as yet unclassified
exampleMany

	^{
			NemoSuggestionEntry new id: 1; data: 'abc'; displayValue: 'abc'.
			NemoSuggestionEntry new id: 2; data: 'def'; displayValue: 'def'.
			NemoSuggestionEntry new id: 3; data: 'ghi'; displayValue: 'ghi'.
			NemoSuggestionEntry new id: 4; data: 'jkl'; displayValue: 'jkl'.
			NemoSuggestionEntry new id: 5; data: 'mno'; displayValue: 'mno'.
			NemoSuggestionEntry new id: 6; data: 'pqr'; displayValue: 'pqr'.
			NemoSuggestionEntry new id: 7; data: 'stu'; displayValue: 'stu'.
			NemoSuggestionEntry new id: 8; data: 'vwx'; displayValue: 'vwx'.
			NemoSuggestionEntry new id: 9; data: 'yz'; displayValue: 'yz'.
		}