as yet unclassified
exampleMany

	^{
			BPSuggestionEntry new id: 1; value: 'abc'.
			BPSuggestionEntry new id: 2; value: 'def'.
			BPSuggestionEntry new id: 3; value: 'ghi'.
			BPSuggestionEntry new id: 4; value: 'jkl'.
			BPSuggestionEntry new id: 5; value: 'mno'.
			BPSuggestionEntry new id: 6; value: 'pqr'.
			BPSuggestionEntry new id: 7; value: 'stu'.
			BPSuggestionEntry new id: 8; value: 'vwx'.
			BPSuggestionEntry new id: 9; value: 'yz'.
		}