spanish documentation
analogias
"
[] Introduccion a las analogias
[] La computadora como el papel
[] El programa como una novela
La abstracciones como capitulos de la novela
[] Los programadores como escribistas
Estamos en la edad media. Solo unos pocos saben leer y escribir. El papel (hardware) ya esta en todos lados; ahora hay que aprender a escribir. 
[] La computadora como una calculadora
	Sirve para resolver problemas concretos. Una calculadora muy versatil, pero calculadora al fin. No para expresar pensamiento. 
[] Un nuevo medio de pensamiento, una nueva forma de comunicacion

[] La gran demanda de programadores
Se necesitan para hacer aplicaciones del modelo 'calculadora'. 

Los usuarios no la ven como un medio para expresar pensamientos. Un ejemplo del nuevo enfoque es la expresion del las matematicas. 


- Pensar en refinamientos sucesivos
Una vez que entiende algo (y lo puede expresar describiendolo adecuadamente en un programa), vuelve a leer lo que ya escribio para encontrar que alguna frase no se entendia. Esto desencadena la reescritura de un nuevo parrafo (metodo) o, en algunos casos, un nuevo capitulo (clase) para expresar mejor dicho concepto. 

- Los programadores como escribistas 
Solamente ellos conocen el lenguaje de los jeroglificos, y como expresar las ideas en ellos.
- Los programadores como analistas
Despues de haber sufrido un buen tiempo con los jeroglificos el programador se transforma en analista. Cual es su nueva tarea? Ser de traductor entre los pedidos del cliente y el team de escribistas (que como es muy dificil llegar a tiempo, se repartiran entre ellos la escritura de los diferentes capitulos). Por que no dejar que el mismo usuario describa sus hechos (el los conoce mejor que nadie)
cita: prefiero enseniarle a un especialista en radares a programar...

- El oscurantismo
- La programacion como descripcion de hechos
- Uno puede ver lo que pasa (ejecucion), pero tambien puede saber por que pasa (lectura del codigo)

- Es inevitable que la computadora sea 'transparente' (el usuario no se da cuenta que esta trabajando con una de ellas) y la gente comience a usarla como medio de expresion de sus ideas. Squeak esta en ese camino. Sus autores apuntan en esta direccion. 
- Java, por motivos practicos y por motivos culturales, no esta en esta direccion, . No nace con la idea que cualquier usuario pueda programar, sino de simplificarle unas cuantas tareas a los programadores (escribistas) existentes. En este sentido sigue la misma linea que C++ porque su fundador queria aprovechar toda la base de programadores C existentes (para enseniarle unos cuantos jeroglificos mas...). Y si seguimos para atras C nace para estar 'C'erca de la maquina; un assembler de (mucho) mas alto nivel.

- End user programming
Hace varios anios que esto es una panacea a la que se ha querido llegar pero siempre resultando en fracasos (lenguajes de muy alto nivel, generador automatico de programas, etc).
Muchos usuarios finales necesitan realizar

- La computadora como una calculadora
- La educacion
La gran masa de gente es 'analfabeta' en esta nueva forma de comunicacion. En realidad nadie sabe bien de que se trata, pero hay unos cuantos indicios de por donde debe ir el camino.

- El futuro de los programadores
Maestros o escritores profesionales.

- El pensamiento matematico en la vida diaria
- Las analogias como cambios de base en espacios vectoriales
- Las matematicas y su notacion precisa pero criptica (solo para iniciados)
- La posibilidad de liberar la matematica de su notacion y re-expresarla en una nueva forma de comunicacion

[que el sistema sea entendible por un individuo]
La mayoria de los sistemas comerciales han sido desarrollados a traves del tiempo por un grupo grande de personas; muchas veces sin llegar a tener una comunicacion fluida entre si, sino que lo hacen por medio de un coordinador. 
Si seguimos la analogia con la escritura, estos sistemas terminan siendo como una novela donde distintas personas escribieron distintos capitulos. El resultado es que es algo imposible de entender por la cantidad de incoherencias, repeticiones de hechos, etc. 
"