spanish documentation
escribistas
"
[que el sistema sea entendible por un individuo]
La mayoria de los sistemas comerciales han sido desarrollados a traves del tiempo por un grupo grande de personas; muchas veces sin llegar a tener una comunicacion fluida entre si, sino que lo hacen por medio de un coordinador. 
Si seguimos la analogia con la escritura, estos sistemas terminan siendo como una novela donde distintas personas escribieron distintos capitulos. El resultado es que es algo imposible de entender por la cantidad de incoherencias, repeticiones de hechos, etc. 
"