spanish documentation
log
"
fg 5/19/2000 20:58. 
- Implementando el braceNode
	- Esto me lleva a implementar primitiveNextPut quien es equivalente a primitiveAtPut.. je, hay que pensarla...

#( 1 ) type allTypes  
addType: 1.0 type

Quiero agregarle un tipo a un IndexedType existente. Me parece que tengo que crear un nuevo tipo a partir del que existia (fijarse que sucede cuando cambio la variable de instancia de un objeto: TPoint new )

"
